services:
  app:
    image: samiamahmood/ds6600-dashboard-project # ds6600-dashboard-project image
    ports:
      - "8050:8050"
    volumes:
      - .:/ds6600-dashboard-project # ds6600-dashboard-project folder/directory from local computer
    networks:
      - dbnetwork

  postgres:
    image: postgres:18.6
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/18/docker
    env_file:
      - .env
    networks:
      - dbnetwork

volumes:
  postgresdata:

networks:
  dbnetwork:
